// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataInfo.proto

package com.crw.nettyinaction.codec.protobufdemo2;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用 data_type 表示传的是哪个枚举类型, 属性1
     * </pre>
     *
     * <code>.BaseMsg.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     * 用 data_type 表示传的是哪个枚举类型, 属性1
     * </pre>
     *
     * <code>.BaseMsg.DataType data_type = 1;</code>
     * @return The dataType.
     */
    com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType getDataType();

    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getStudent();
    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     */
    com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder getStudentOrBuilder();

    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return Whether the teacher field is set.
     */
    boolean hasTeacher();
    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return The teacher.
     */
    com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getTeacher();
    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     */
    com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder getTeacherOrBuilder();

    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   * protobuf 可以使用 message 管理其他 message
   * </pre>
   *
   * Protobuf type {@code BaseMsg}
   */
  public  static final class BaseMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_BaseMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.Builder.class);
    }

    /**
     * <pre>
     * 定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code BaseMsg.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * proto3 要求枚举类型从下标0开始
       * </pre>
       *
       * <code>STUDENT = 0;</code>
       */
      STUDENT(0),
      /**
       * <code>TEACHER = 1;</code>
       */
      TEACHER(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * proto3 要求枚举类型从下标0开始
       * </pre>
       *
       * <code>STUDENT = 0;</code>
       */
      public static final int STUDENT_VALUE = 0;
      /**
       * <code>TEACHER = 1;</code>
       */
      public static final int TEACHER_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return STUDENT;
          case 1: return TEACHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BaseMsg.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STUDENT(2),
      TEACHER(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return TEACHER;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     * 用 data_type 表示传的是哪个枚举类型, 属性1
     * </pre>
     *
     * <code>.BaseMsg.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     * 用 data_type 表示传的是哪个枚举类型, 属性1
     * </pre>
     *
     * <code>.BaseMsg.DataType data_type = 1;</code>
     * @return The dataType.
     */
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType result = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.valueOf(dataType_);
      return result == null ? com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.UNRECOGNIZED : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    public boolean hasStudent() {
      return dataBodyCase_ == 2;
    }
    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getStudent() {
      if (dataBodyCase_ == 2) {
         return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_;
      }
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
    }
    /**
     * <pre>
     * 属性2
     * </pre>
     *
     * <code>.Student student = 2;</code>
     */
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_;
      }
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
    }

    public static final int TEACHER_FIELD_NUMBER = 3;
    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return Whether the teacher field is set.
     */
    public boolean hasTeacher() {
      return dataBodyCase_ == 3;
    }
    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return The teacher.
     */
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getTeacher() {
      if (dataBodyCase_ == 3) {
         return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_;
      }
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
    }
    /**
     * <pre>
     * 属性3
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     */
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder getTeacherOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_;
      }
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.STUDENT.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.STUDENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg)) {
        return super.equals(obj);
      }
      com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg other = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getTeacher()
              .equals(other.getTeacher())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * protobuf 可以使用 message 管理其他 message
     * </pre>
     *
     * Protobuf type {@code BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMsg)
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_BaseMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.Builder.class);
      }

      // Construct using com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_BaseMsg_descriptor;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg getDefaultInstanceForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg build() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg buildPartial() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg result = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (teacherBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = teacherBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg) {
          return mergeFrom((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg other) {
        if (other == com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       * 用 data_type 表示传的是哪个枚举类型, 属性1
       * </pre>
       *
       * <code>.BaseMsg.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       * 用 data_type 表示传的是哪个枚举类型, 属性1
       * </pre>
       *
       * <code>.BaseMsg.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用 data_type 表示传的是哪个枚举类型, 属性1
       * </pre>
       *
       * <code>.BaseMsg.DataType data_type = 1;</code>
       * @return The dataType.
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType result = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.valueOf(dataType_);
        return result == null ? com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 用 data_type 表示传的是哪个枚举类型, 属性1
       * </pre>
       *
       * <code>.BaseMsg.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用 data_type 表示传的是哪个枚举类型, 属性1
       * </pre>
       *
       * <code>.BaseMsg.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder> studentBuilder_;
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return dataBodyCase_ == 2;
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       * @return The student.
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_;
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder mergeStudent(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance()) {
            dataBody_ = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.newBuilder((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_;
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 属性2
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder>(
                  (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder> teacherBuilder_;
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       * @return Whether the teacher field is set.
       */
      public boolean hasTeacher() {
        return dataBodyCase_ == 3;
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       * @return The teacher.
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_;
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return teacherBuilder_.getMessage();
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder mergeTeacher(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher value) {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance()) {
            dataBody_ = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.newBuilder((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder getTeacherOrBuilder() {
        if ((dataBodyCase_ == 3) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_;
          }
          return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 属性3
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder>(
                  (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return teacherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:BaseMsg)
    private static final com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg();
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @java.lang.Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student)) {
        return super.equals(obj);
      }
      com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student other = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.Builder.class);
      }

      // Construct using com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getDefaultInstanceForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student build() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student buildPartial() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student result = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) {
          return mergeFrom((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student other) {
        if (other == com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student();
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teacher();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher)) {
        return super.equals(obj);
      }
      com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher other = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.class, com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.Builder.class);
      }

      // Construct using com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getDefaultInstanceForType() {
        return com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher build() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher buildPartial() {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher result = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) {
          return mergeFrom((com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher other) {
        if (other == com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher();
    }

    public static com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.crw.nettyinaction.codec.protobufdemo2.DataInfo.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DataInfo.proto\"\233\001\n\007BaseMsg\022$\n\tdata_typ" +
      "e\030\001 \001(\0162\021.BaseMsg.DataType\022\033\n\007student\030\002 " +
      "\001(\0132\010.StudentH\000\022\033\n\007teacher\030\003 \001(\0132\010.Teach" +
      "erH\000\"$\n\010DataType\022\013\n\007STUDENT\020\000\022\013\n\007TEACHER" +
      "\020\001B\n\n\010dataBody\"0\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n" +
      "\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\"0\n\007Teacher\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005B7\n)co" +
      "m.crw.nettyinaction.codec.protobufdemo2B" +
      "\010DataInfoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMsg_descriptor,
        new java.lang.String[] { "DataType", "Student", "Teacher", "DataBody", });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
